[package]
name = "twizzler-kernel"
version = "0.1.0"
edition = "2021"


[dependencies]
bitflags = "*"
uart_16550 = "0.2.0"
spin = "*"
x86 = "*"
x86_64 = "*"
linked_list_allocator = "*"
backtracer_core = {git = "https://github.com/gz/backtracer"}
object = {version = "0.27", default-features = false, features = ["read"]}
addr2line = { version = "0.16", default-features = false, features = ["rustc-demangle"] }
slabmalloc = "*"
fixedbitset = {version = "*", default-features = false}
acpi = "*"
stivale-boot = "*"
xmas-elf = "*"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
