[package]
name = "rustkernel"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
bitflags = "*"
uart_16550 = "0.2.0"
spin = "*"
x86 = "*"
x86_64 = "*"
linked_list_allocator = "*"
backtracer_core = {git = "https://github.com/gz/backtracer"}
object = {version = "0.27", default-features = false, features = ["read"]}
#stable_deref_trait = { version = "1.1.0", default-features = false, features = ["alloc"] }
#gimli = { version = "0.25", default-features = false, features = ["read", "endian-reader", "stable_deref_trait"] }
addr2line = { version = "0.16", default-features = false, features = ["rustc-demangle"] }
slabmalloc = "*"
fixedbitset = {version = "*", default-features = false}
acpi = "*"
stivale-boot = "*"
xmas-elf = "*"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
