[workspace]
members = [
    "tools/xtask",
    "tools/image_builder",
    "src/bin/init",
    "src/kernel",
]

[workspace.metadata]
initrd-members = ["init"]
tools = ["image_builder"]
kernel = ["twizzler-kernel"]

[profile.release]
debug = true