[workspace]
members = [
    "tools/xtask",
    "tools/image_builder",
    "tools/initrd_gen",
    "src/bin/init",
    "src/bin/devmgr",
    "src/kernel",
    "src/lib/twizzler-queue-raw"
]
resolver = "2"

[workspace.metadata]
twizzler-apps = ["init", "devmgr"]
tools = ["image_builder", "initrd_gen"]
kernel = ["twizzler-kernel"]
initrd-members = ["init", "devmgr"]
checks = ["twizzler-queue-raw"]

[profile.release]
debug = true

[patch.'https://github.com/dbittman/twizzler-abi']
twizzler-abi = { path = "src/lib/twizzler-abi" }