[workspace]
members = [
    "tools/xtask",
    "tools/image_builder",
    "tools/initrd_gen",
    "src/bin/init",
    "src/kernel",
]
resolver = "2"

[workspace.metadata]
twizzler-apps = ["init"]
tools = ["image_builder", "initrd_gen"]
kernel = ["twizzler-kernel"]
initrd-members = ["init"]

[profile.release]
debug = true

[patch.'https://github.com/dbittman/twizzler-abi']
twizzler-abi = { path = "src/lib/twizzler-abi" }