[alias]
xtask = "run --package xtask --"
check-all = "run --package xtask -- check-all"
build-all = "run --package xtask -- build-all"
make-disk = "run --package xtask -- make-disk"
start-qemu = "run --package xtask -- start-qemu"
bootstap = "run --package xtask -- bootstrap"

[build]
rustdocflags = "-Zunstable-options --enable-index-page"