[alias]
xtask = "run --package xtask --"
check-all = "run --package xtask -- check-all"
build-all = "run --package xtask -- build-all"
make-disk = "run --package xtask -- make-disk"
start-qemu = "run --package xtask -- start-qemu"
bootstrap = "run --package xtask -- bootstrap"
build-std = "run --package xtask -- build-std"

[build]
rustdocflags = "-Zunstable-options --enable-index-page"