# Includes one of the default files in src/bootstrap/defaults
profile = "user"
changelog-seen = 2

[install]
prefix = "../../install"
sysconfdir = "etc"

[llvm]
#download-ci-llvm = true
skip-rebuild = false

[build]
tools = ["clippy", "rustfmt", "src"] # + "rust-demangler" if `profiler`
docs = false
target = ["x86_64-unknown-twizzler"]
submodules = false

[rust]
lld = true
llvm-tools = true
llvm-libunwind = 'in-tree'
