[package]
name = "unittest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "*"
serde_json = "*"
monitor-api = { path = "../../rt/monitor-api" }
unittest-report = { path = "unittest-report" }
